### ISSUE TITLE
Definition of sky_center_freq?

### ISSUE THREAD

**Issue by caseyjlaw** [demorest/evla_mcast#9]
I realized that I don't actually know how the scan configuration's "sky_center_freq" is defined:
https://github.com/realfastvla/evla_mcast/blob/f2628955952b64b491b8cf4cb45e285271703527/evla_mcast/scan_config.py#L438.
Is that the center of the subband or channel 0?

**Comment by demorest** [comment]
That is the center frequency of the subband.

**Comment by caseyjlaw** [comment]
Sorry for the silly question. I somehow assumed otherwise a while back when writing a function to parse scan configs.
